"""Versioned domain vocabulary shared by every product surface."""

from enum import StrEnum


class CampaignState(StrEnum):
    PROPOSED = "PROPOSED"
    INVENTORIED = "INVENTORIED"
    MIGRATING = "MIGRATING"
    RECONCILING = "RECONCILING"
    READY = "READY"
    RETIRED = "RETIRED"
    BLOCKED = "BLOCKED"


class ConsumerDisposition(StrEnum):
    DISCOVERED = "DISCOVERED"
    IDENTIFIED = "IDENTIFIED"
    CHANGE_PROPOSED = "CHANGE_PROPOSED"
    APPLIED = "APPLIED"
    VALIDATED = "VALIDATED"
    REMOVED = "REMOVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    WAIVED = "WAIVED"
    OPAQUE = "OPAQUE"
    UNRESOLVED = "UNRESOLVED"
    STALE = "STALE"
    FAILED = "FAILED"


class Decision(StrEnum):
    READY_TO_RETIRE = "READY_TO_RETIRE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    UNSAFE = "UNSAFE"


class EvidenceMode(StrEnum):
    LIVE = "live"
    FIXTURE = "fixture"
    REPLAY = "replay"
    ANALYSIS = "analysis"


class EvidenceStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    UNKNOWN = "UNKNOWN"
    UNAVAILABLE = "UNAVAILABLE"
    STALE = "STALE"


class RefusalCode(StrEnum):
    SPEC_PARSE_FAILED = "SPEC_PARSE_FAILED"
    SPEC_SCHEMA_INVALID = "SPEC_SCHEMA_INVALID"
    SPEC_IDENTICAL_FIELDS = "SPEC_IDENTICAL_FIELDS"
    SPEC_UNSUPPORTED_REPLACEMENT = "SPEC_UNSUPPORTED_REPLACEMENT"
    SPEC_REPLACEMENT_INCOMPATIBLE = "SPEC_REPLACEMENT_INCOMPATIBLE"
    EVIDENCE_REQUIRED_SOURCE_INCOMPLETE = "EVIDENCE_REQUIRED_SOURCE_INCOMPLETE"
    EVIDENCE_MODE_NOT_LIVE = "EVIDENCE_MODE_NOT_LIVE"
    IDENTITY_NOT_FOUND = "IDENTITY_NOT_FOUND"
    IDENTITY_AMBIGUOUS = "IDENTITY_AMBIGUOUS"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    SOURCE_FINGERPRINT_MISMATCH = "SOURCE_FINGERPRINT_MISMATCH"
    SCOPE_PATH_OUTSIDE_ROOT = "SCOPE_PATH_OUTSIDE_ROOT"
    SCOPE_TARGET_NOT_ALLOWED = "SCOPE_TARGET_NOT_ALLOWED"
    INTEGRITY_DIGEST_MISMATCH = "INTEGRITY_DIGEST_MISMATCH"
